apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: di2kbyy4e-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: di2kbyy4e-python 
  name: di2kbyy4e-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: di2kbyy4e-python 
